### ISSUE TITLE
请教关于C++编写Basler相机接口

### ISSUE THREAD

**Issue by squirrelfeng** [xianyupro/xianyupro.github.io#1]

**Comment by squirrelfeng** [comment]
你好，尝试了你的Basler接口，在采集图片时，几张图后直接提示Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
请问怎么回事
谢谢！

**Comment by xianyupro** [comment]
> 你好，尝试了你的Basler接口，在采集图片时，几张图后直接提示Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object. 请问怎么回事 谢谢！

你好，根据你的反馈我这边也不好定位问题，但方便的话你可以贴出所出问题的代码。

**Comment by squirrelfeng** [comment]
> 

抱歉时隔快一年才回复您，因为后来我用pylon.net操作win版了。 但是这个还是一直困惑我好几天，我将代码传到GitHub了： https://github.com/squirrelfeng/BaslerCameraTest，我直接在windows下编译测试运行的。
现状是：执行连续拍照后，每次拍完3张照片（模拟相机测试的），C++的m_handler就会崩溃，提示标题错误。我以为是GC，但是尝试GC.KeepAlive也不行。
如果可能的话，希望您能帮忙看看，可以有偿支持一下，谢谢！！！

[截图](https://sm.ms/image/57EJmoPzk9tSYsp)
